### ISSUE TITLE
[P4A-3] CSRF implementation

### ISSUE THREAD

**Issue by allenpoon** [ierg4210/shop22#3]
Your CSRF value is not implement well
Your CSRF server code is printed to client side
![aa](https://cloud.githubusercontent.com/assets/3294681/7509728/2219078e-f4c7-11e4-8398-2edea63a758a.png)
From: http://store22.ierg4210.org/account/login/account

**Comment by s1155030186** [comment]
Same issue is posted 
I have changed it already
