### ISSUE TITLE
[P4A-3] Incorrect implement of CSRF in login page

### ISSUE THREAD

**Issue by s1155035143** [ierg4210/shop22#4]
![screen shot 2015-05-07 at 2 17 55 pm](https://cloud.githubusercontent.com/assets/10654935/7509707/ecd3017e-f4c6-11e4-911a-85f0c044c188.png)

![screen shot 2015-05-07 at 2 35 20 pm](https://cloud.githubusercontent.com/assets/10654935/7509740/3dc035de-f4c7-11e4-9963-fbe63feabc92.png)

Commit: 46b533b

Problem: the CSRF input field in login page is rendered incorrectly, i.e. the source JS outputed. 

Possible solution: in routes/frontend.js, line 117 and 119, the req.csrfToken should be req.csrfToken()

**Comment by s1155035143** [comment]
Haha. One minute late than issue #3 .

Please close this issue after fixing the issue :)

**Comment by s1155030186** [comment]
ok Thanks for ur reminder, I have fixed it
